import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://stg83.octosglobal.info/tss_2025/")
    page.locator("#tss-rep-sec").click()
    page.locator(".video-btn").first.click()
    page.get_by_role("button", name="Close").click()
    page.get_by_role("link", name="Explore More").click()
    page.get_by_role("link", name="Manufacturers").click()
    page.get_by_role("link", name="BVC").click()
    page.get_by_role("link", name="Machinery").click()
    page.get_by_role("link", name="Auxillary IG-Equipment").click()
    page.get_by_role("link", name="View More").first.click()
    page.get_by_role("link", name="Get A Quote").nth(1).click()
    page.get_by_role("textbox", name="First Name *").click()
    page.get_by_role("textbox", name="First Name *").fill("Martin")
    page.get_by_role("textbox", name="Last Name *").click()
    page.get_by_role("textbox", name="Last Name *").fill("Gill")
    page.get_by_role("textbox", name="Email *").click()
    page.get_by_role("textbox", name="Email *").fill("martin@mailinatyor.com")
    page.get_by_role("textbox", name="Email *").press("ArrowLeft")
    page.get_by_role("textbox", name="Email *").press("ArrowLeft")
    page.get_by_role("textbox", name="Email *").press("ArrowLeft")
    page.get_by_role("textbox", name="Email *").fill("martin@mailinator.com")
    page.get_by_role("textbox", name="Phone Number *").click()
    page.get_by_role("textbox", name="Phone Number *").fill("648-223-1502")
    page.get_by_role("textbox", name="Company Name *").click()
    page.get_by_role("textbox", name="Company Name *").fill("Glass pvt limited")
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("link", name="Labels & Sample Boxes").click()
    page.locator(".w-100").first.click()
    page.get_by_role("button", name="Close").click()
    page.locator("div:nth-child(3) > .block-inner > .block-image > .w-100").click()
    page.get_by_role("button", name="Close").click()
    page.get_by_role("link", name="Consumables").click()
    page.get_by_role("link", name="CNC Pods").click()
    page.get_by_role("img", name="banner image").nth(1).click()
    page.get_by_role("button", name="Close").click()
    page.get_by_role("link", name="View More").first.click()
    page.goto("https://stg83.octosglobal.info/tss_2025/consumables/cnc-pod")
    page.get_by_role("link", name="View More").nth(1).click()
    expect(page.locator("#navbarNav")).to_match_aria_snapshot("- link \"Grizzly\":\n  - /url: https://stg83.octosglobal.info/tss_2025/grizzly\n  - text: \"\"\n  - img")
    page.get_by_role("link", name="Grizzly").click()
    page.get_by_role("link", name="search-icon", exact=True).click()
    page.get_by_role("textbox", name="Search here").click()
    page.get_by_role("textbox", name="Search here").fill("i")
    page.locator(".manufacturer-list > div:nth-child(2)").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
